package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
)

// import u001 from '!!raw-loader!../../../../../public/img/icons/unicons/angle-double-down.svg';

// cacheItem(u001, unicons, 'angle-double-down');

func main() {
	file, err := os.Open("cmd/genbundle/bundle.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	count := 1000

	fmt.Printf("// This file was autogenerated from\n")
	fmt.Printf("// https://github.com/grafana/icons\n\n")

	fmt.Printf("import { cacheStore } from '@leeoniya/react-inlinesvg';\n")
	fmt.Printf("const iconRoot = 'public/img/icons/';\n\n")

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		count++

		if !strings.HasSuffix(line, ".svg") {
			line += ".svg"
		}

		fmt.Printf("import u%d from '!!raw-loader!../../../../../public/img/icons/%s';\n", count, line)
		fmt.Printf("cacheStore[iconRoot + '%s'] = { content: u%d, status: 'loaded', queue: [] };\n\n", line, count)
	}

	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("done!\n")

}
